import { SynthParameters } from './types';

export const SYNTH_PRESETS: Record<string, { name: string; category: string; params: SynthParameters }> = {
  glassBell: {
    name: 'Glass Bell',
    category: 'Pluck & Bell',
    params: {
      oscType: 'sine',
      subOsc: true,
      subOscLevel: 0.25,
      detune: 4,
      attack: 0.005,
      decay: 0.8,
      sustain: 0.1,
      release: 1.2,
      filterCutoff: 4500,
      filterResonance: 4.5,
      filterEnvAmount: 0.6,
      lfoRate: 3.5,
      lfoDepth: 0.15,
      lfoTarget: 'pitch',
      chorus: 0.4,
      delayTime: 0.35,
      delayFeedback: 0.45,
      reverb: 0.65,
      distortion: 0.02
    }
  },
  etherealPad: {
    name: 'Ethereal Glass Pad',
    category: 'Pad',
    params: {
      oscType: 'sawtooth',
      subOsc: true,
      subOscLevel: 0.4,
      detune: 12,
      attack: 0.85,
      decay: 1.2,
      sustain: 0.75,
      release: 2.2,
      filterCutoff: 2200,
      filterResonance: 3.2,
      filterEnvAmount: 0.3,
      lfoRate: 0.8,
      lfoDepth: 0.3,
      lfoTarget: 'filter',
      chorus: 0.65,
      delayTime: 0.42,
      delayFeedback: 0.5,
      reverb: 0.8,
      distortion: 0.0
    }
  },
  warmAnalogBass: {
    name: 'Warm Analog 808 Bass',
    category: 'Bass',
    params: {
      oscType: 'triangle',
      subOsc: true,
      subOscLevel: 0.7,
      detune: 0,
      attack: 0.01,
      decay: 0.4,
      sustain: 0.85,
      release: 0.3,
      filterCutoff: 950,
      filterResonance: 2.0,
      filterEnvAmount: 0.5,
      lfoRate: 1.0,
      lfoDepth: 0.0,
      lfoTarget: 'filter',
      chorus: 0.1,
      delayTime: 0.0,
      delayFeedback: 0.0,
      reverb: 0.15,
      distortion: 0.25
    }
  },
  neoSoulKeys: {
    name: 'Neo-Soul Rhodes',
    category: 'Keys',
    params: {
      oscType: 'sine',
      subOsc: true,
      subOscLevel: 0.2,
      detune: 6,
      attack: 0.015,
      decay: 0.9,
      sustain: 0.4,
      release: 0.8,
      filterCutoff: 3200,
      filterResonance: 1.8,
      filterEnvAmount: 0.4,
      lfoRate: 4.8,
      lfoDepth: 0.22,
      lfoTarget: 'pan',
      chorus: 0.5,
      delayTime: 0.25,
      delayFeedback: 0.3,
      reverb: 0.45,
      distortion: 0.05
    }
  },
  cyberPulseLead: {
    name: 'Cyber Pulse Lead',
    category: 'Lead',
    params: {
      oscType: 'square',
      subOsc: true,
      subOscLevel: 0.3,
      detune: 15,
      attack: 0.02,
      decay: 0.35,
      sustain: 0.6,
      release: 0.5,
      filterCutoff: 3800,
      filterResonance: 5.5,
      filterEnvAmount: 0.7,
      lfoRate: 6.0,
      lfoDepth: 0.2,
      lfoTarget: 'pitch',
      chorus: 0.35,
      delayTime: 0.3,
      delayFeedback: 0.4,
      reverb: 0.5,
      distortion: 0.35
    }
  },
  lofiPluck: {
    name: 'Lo-Fi Kalimba Pluck',
    category: 'Pluck & Bell',
    params: {
      oscType: 'triangle',
      subOsc: false,
      subOscLevel: 0.0,
      detune: 3,
      attack: 0.005,
      decay: 0.45,
      sustain: 0.05,
      release: 0.4,
      filterCutoff: 1800,
      filterResonance: 2.5,
      filterEnvAmount: 0.3,
      lfoRate: 0.5,
      lfoDepth: 0.1,
      lfoTarget: 'pitch',
      chorus: 0.3,
      delayTime: 0.38,
      delayFeedback: 0.35,
      reverb: 0.5,
      distortion: 0.08
    }
  }
};
